namespace: calculator

image:
  repository: shayr30/calculator-divide
  tag: v4
  pullPolicy: Always

replicaCount: 1

temporal:
  host: temporal-frontend.temporal.svc.cluster.local
  port: 7233
  namespace: temporal

taskQueue: queue-div

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi