namespace: calculator

image:
  repository: shayr30/calculator-workflow
  tag: v5
  pullPolicy: Always

replicaCount: 1

temporal:
  host: temporal-frontend.temporal.svc.cluster.local
  port: 7233
  namespace: calc

taskQueue: queue-workflow

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi