apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-workflow
  namespace: {{ .Values.namespace }}
  labels:
    app: calculator
    component: workflow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: calculator
      component: workflow
  template:
    metadata:
      labels:
        app: calculator
        component: workflow
    spec:
      containers:
      - name: workflow
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: calculator-config
        env:
        - name: WORKER_TASK_QUEUE
          value: {{ .Values.taskQueue }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}